// <auto-generated />
namespace POS_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _1stDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1stDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202112202133402_1stDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
